language: scala
sudo: required
dist: trusty

jdk:
  - oraclejdk8

matrix:
  include:
  - stage: build
    env: CI_SCRIPT=ci/test-mill-0.sh
  - stage: build
    env: CI_SCRIPT=ci/test-mill-1.sh
  - stage: build
    env: CI_SCRIPT=ci/test-mill-2.sh
  - stage: build
    env: CI_SCRIPT=ci/test-mill-dev.sh
  - stage: build
    env: CI_SCRIPT=ci/test-mill-release.sh
  - stage: release
    env: CI_SCRIPT="ci/on-master.py ci/release.sh"
  - stage: release
    env: CI_SCRIPT="ci/on-master.py ci/publish-docs.sh"

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.1.3/0.1.3 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - "$CI_SCRIPT"

cache:
  directories:
  - $HOME/.coursier